import React, { createContext, useState, useContext } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    logo: "Booking.com",
    signUp: "Sign Up",
    login: "Login",
    logout: "Logout",
    transactions: "Transactions",
    heroTitle: "Find your next stay",
    heroDesc: "Search deals on hotels, homes, and much more...",
    searchPlaceholder: "Where are you going?",
    searchBtn: "Search",
    adult: "Adult",
    children: "Children",
    room: "Room",
    browseType: "Browse by property type",
    homesLove: "Homes guests love",
    bookNow: "Book Now!",
    reserve: "Reserve",
    excellent: "Excellent",
    exceptional: "Exceptional",
    startingFrom: "Starting from",
    signInTitle: "Sign In",
    signUpTitle: "Sign Up",
    welcomeBack: "Welcome back! Enter your details to continue.",
    createAccountDesc: "Create an account to start booking stays.",
    username: "Username",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    password: "Password",
    createAccountBtn: "Create Account",
    loginBtn: "Login",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    yourTransactions: "Your Transactions",
    deleteCanceled: "Delete Canceled Transactions",
    hotel: "Hotel",
    roomLabel: "Room",
    roomNumbersLabel: "Room Numbers",
    date: "Date",
    price: "Price",
    paymentMethod: "Payment Method",
    status: "Status",
    action: "Action",
    cancel: "Cancel",
    loading: "Loading...",
    noTransactions: "No transactions found",
    deleteCanceledAlert: "Deleted {count} canceled transactions.",
    cancelSuccessAlert: "Transaction canceled successfully.",
    bookingSuccessAlert: "Booking successful!",
    fullname: "Full Name",
    identityCard: "Identity Card",
    bank: "Bank",
    accountNumber: "Account Number",
    selectRooms: "Select Rooms",
    payment: "Payment Method",
    selectPayment: "Select Payment Method",
    cash: "Cash",
    creditCard: "Credit Card",
    searchDestAlert: "Please enter a destination to search.",
    hanoi: "Ha Noi",
    hcm: "Ho Chi Minh",
    danang: "Da Nang",
    properties: "properties",
    stays: "Stays",
    flights: "Flights",
    flightHotel: "Flight + Hotel",
    carRentals: "Car rentals",
    attractions: "Attractions",
    airportTaxis: "Airport taxis",
    addFlights: "Add flights to my search",
    whyBookingTitle: "Why Booking.com?",
    feature1Title: "Book now, pay at the property",
    feature1Desc: "With free cancellation on most rooms",
    feature2Title: "500M+ reviews from travelers",
    feature2Desc: "Verified reviews from real guests",
    feature3Title: "2+ million properties worldwide",
    feature3Desc: "Hotels, homes, apartments, and more",
    feature4Title: "Trusted 24/7 customer service",
    feature4Desc: "Support in 40+ languages",
    seeAvailability: "See availability",
    taxesAndFees: "Includes taxes and fees",
    freeCancelSubtitle: "You can cancel later, so lock in this great price today!",
    destinationLabel: "Destination",
    checkInDate: "Check-in Date",
    optionsLabel: "Options",
    minPriceLabel: "Min price per night",
    maxPriceLabel: "Max price per night",
    searchTitle: "Search",
    showMap: "Show map",
    locationRating: "Excellent location",
    reviewsCount: "reviews",
    mailTitle: "Save time, save money!",
    mailDesc: "Sign up and we'll send the best deals to you",
    mailPlaceholder: "Your Email",
    subscribeBtn: "Subscribe",
    hotelPlural: "Hotels",
    apartmentPlural: "Apartments",
    resortPlural: "Resorts",
    villaPlural: "Villas",
    cabinPlural: "Cabins",
    listYourProperty: "List your property",
    workTrip: "I'm traveling for work",
    searchBtnShort: "Search",
  },
  vi: {
    logo: "Booking.com",
    signUp: "Đăng ký",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    transactions: "Giao dịch",
    heroTitle: "Tìm chỗ nghỉ tiếp theo",
    heroDesc: "Tìm ưu đãi khách sạn, chỗ nghỉ dạng nhà và nhiều hơn nữa...",
    searchPlaceholder: "Bạn muốn đi đâu?",
    searchBtn: "Tìm kiếm",
    adult: "Người lớn",
    children: "Trẻ em",
    room: "Phòng",
    browseType: "Tìm theo loại chỗ nghỉ",
    homesLove: "Nhà khách yêu thích",
    bookNow: "Đặt ngay!",
    reserve: "Đặt phòng",
    excellent: "Tuyệt vời",
    exceptional: "Xuất sắc",
    startingFrom: "Giá chỉ từ",
    signInTitle: "Đăng nhập",
    signUpTitle: "Đăng ký",
    welcomeBack: "Chào mừng quay trở lại! Vui lòng nhập thông tin chi tiết.",
    createAccountDesc: "Tạo tài khoản để bắt đầu đặt chỗ nghỉ.",
    username: "Tên đăng nhập",
    phoneNumber: "Số điện thoại",
    emailAddress: "Địa chỉ Email",
    password: "Mật khẩu",
    createAccountBtn: "Tạo tài khoản",
    loginBtn: "Đăng nhập",
    alreadyHaveAccount: "Đã có tài khoản?",
    dontHaveAccount: "Chưa có tài khoản?",
    yourTransactions: "Giao dịch của bạn",
    deleteCanceled: "Xóa giao dịch đã hủy",
    hotel: "Khách sạn",
    roomLabel: "Loại phòng",
    roomNumbersLabel: "Số phòng",
    date: "Ngày đặt",
    price: "Giá tiền",
    paymentMethod: "Phương thức",
    status: "Trạng thái",
    action: "Hành động",
    cancel: "Hủy phòng",
    loading: "Đang tải...",
    noTransactions: "Không có giao dịch nào",
    deleteCanceledAlert: "Đã xóa {count} giao dịch đã hủy.",
    cancelSuccessAlert: "Đã hủy giao dịch thành công.",
    bookingSuccessAlert: "Đặt phòng thành công!",
    fullname: "Họ và tên",
    identityCard: "Số CMND/CCCD",
    bank: "Ngân hàng",
    accountNumber: "Số tài khoản",
    selectRooms: "Chọn phòng đặt",
    payment: "Thanh toán",
    selectPayment: "Chọn phương thức thanh toán",
    cash: "Tiền mặt",
    creditCard: "Thẻ tín dụng",
    searchDestAlert: "Vui lòng nhập điểm đến để tìm kiếm.",
    hanoi: "Hà Nội",
    hcm: "Hồ Chí Minh",
    danang: "Đà Nẵng",
    properties: "chỗ nghỉ",
    stays: "Lưu trú",
    flights: "Chuyến bay",
    flightHotel: "Chuyến bay + Khách sạn",
    carRentals: "Thuê xe",
    attractions: "Địa điểm tham quan",
    airportTaxis: "Taxi sân bay",
    addFlights: "Thêm chuyến bay vào phần tìm kiếm",
    whyBookingTitle: "Tại sao chọn Booking.com?",
    feature1Title: "Đặt bây giờ, thanh toán tại chỗ nghỉ",
    feature1Desc: "Có thể hủy miễn phí ở hầu hết các phòng",
    feature2Title: "Hơn 500 triệu đánh giá từ khách du lịch",
    feature2Desc: "Đánh giá đã được xác thực từ khách thực tế",
    feature3Title: "Hơn 2 triệu chỗ nghỉ trên toàn thế giới",
    feature3Desc: "Khách sạn, nhà nghỉ, căn hộ và nhiều hơn nữa",
    feature4Title: "Hỗ trợ khách hàng 24/7 uy tín",
    feature4Desc: "Hỗ trợ bằng hơn 40 ngôn ngữ",
    seeAvailability: "Xem chỗ trống",
    taxesAndFees: "Đã bao gồm thuế và phí",
    freeCancelSubtitle: "Bạn có thể hủy sau, nên hãy chốt ngay hôm nay để nhận giá tốt này!",
    destinationLabel: "Điểm đến",
    checkInDate: "Ngày nhận phòng",
    optionsLabel: "Tùy chọn",
    minPriceLabel: "Giá tối thiểu / đêm",
    maxPriceLabel: "Giá tối đa / đêm",
    searchTitle: "Tìm kiếm",
    showMap: "Xem bản đồ",
    locationRating: "Vị trí tuyệt vời",
    reviewsCount: "đánh giá",
    mailTitle: "Tiết kiệm thời gian, tiết kiệm tiền bạc!",
    mailDesc: "Đăng ký nhận bản tin để chúng tôi gửi các ưu đãi tốt nhất cho bạn",
    mailPlaceholder: "Địa chỉ Email của bạn",
    subscribeBtn: "Đăng ký nhận tin",
    hotelPlural: "Khách sạn",
    apartmentPlural: "Căn hộ",
    resortPlural: "Khu nghỉ dưỡng",
    villaPlural: "Biệt thự",
    cabinPlural: "Nhà gỗ",
    listYourProperty: "Đăng chỗ nghỉ của Quý vị",
    workTrip: "Tôi đi công tác",
    searchBtnShort: "Tìm",
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem("lang") || "vi");

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem("lang", newLang);
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
